spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: trip-booking-service-temporal
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: trip-booking-temporal-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.travelbooking.*"

temporal:
  service-address: localhost:7233
  namespace: default
  task-queue: trip-booking-queue