spring:
  application:
    name: flight-service
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/flightdb}
    username: ${DATABASE_USER:flightuser}
    password: ${DATABASE_PASSWORD:flightpass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: flight-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.travelbooking: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg [correlationId=%X{correlationId}]%n"