server:
  port: 8085

spring:
  application:
    name: trip-booking-service-temporal
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: trip-booking-temporal-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.travelbooking.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

temporal:
  service-address: ${TEMPORAL_SERVICE_ADDRESS:localhost:7233}
  namespace: default
  task-queue: trip-booking-queue

logging:
  level:
    com.travelbooking: DEBUG
    io.temporal: INFO