name: Travel Booking POJO CI Pipeline

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'travel-booking-pojo/**'
      - '.github/workflows/travel-booking-pojo-ci.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'travel-booking-pojo/**'
      - '.github/workflows/travel-booking-pojo-ci.yml'

defaults:
  run:
    working-directory: travel-booking-pojo

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --build-cache --no-daemon

      - name: Generate test report
        if: always()
        run: ./gradlew jacocoTestReport --build-cache --no-daemon

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: travel-booking-pojo/build/test-results/test/

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: travel-booking-pojo/build/reports/jacoco/test/

      - name: Build JAR
        run: ./gradlew bootJar --build-cache --no-daemon

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: travel-booking-pojo/build/libs/*.jar