name: Travel Booking POJO CI Pipeline

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'travel-booking-pojo/**'
      - '.github/workflows/travel-booking-pojo-ci.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'travel-booking-pojo/**'
      - '.github/workflows/travel-booking-pojo-ci.yml'

defaults:
  run:
    working-directory: travel-booking-pojo

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: travel_user
          POSTGRES_PASSWORD: travel_password
          POSTGRES_DB: travel_booking
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon
        env:
          DB_URL: jdbc:postgresql://localhost:5432/travel_booking
          DB_USERNAME: travel_user
          DB_PASSWORD: travel_password

      - name: Generate test report
        if: always()
        run: ./gradlew jacocoTestReport --no-daemon

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: travel-booking-pojo/build/test-results/test/

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: travel-booking-pojo/build/reports/jacoco/test/

      - name: Build JAR
        run: ./gradlew bootJar --no-daemon

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: travel-booking-pojo/build/libs/*.jar