name: Travel Booking Kafka CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'travel-booking-spring-kafka/**'
      - '.github/workflows/travel-booking-kafka-ci.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'travel-booking-spring-kafka/**'
      - '.github/workflows/travel-booking-kafka-ci.yml'

defaults:
  run:
    working-directory: travel-booking-spring-kafka

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: travel-booking-spring-kafka
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: travel-booking-spring-kafka
      run: ./gradlew clean build

    - name: Run tests
      working-directory: travel-booking-spring-kafka
      run: ./gradlew test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: travel-booking-spring-kafka/**/build/test-results/test/TEST-*.xml

    - name: Build Docker images
      working-directory: travel-booking-spring-kafka
      run: |
        ./gradlew bootJar
        for service in trip-booking-service flight-service hotel-service car-rental-service discount-service; do
          if [ -f $service/Dockerfile ]; then
            docker build -t travel-booking/$service:latest $service/
          fi
        done